### ISSUE TITLE
Follow up on MacOS support

### ISSUE THREAD

**Issue by pierreglaser** [pierreglaser/inkscape-figures#1]
Follow up on gillescastel/inkscape-figures#11
@BerryTaylor

**Comment by BerryTaylor** [comment]
Here I am! So can you find the error cause of your code?

**Comment by BerryTaylor** [comment]
Or maybe we can use TeamViewer to let you see the problem of the code on my Mac more clearly.

**Comment by pierreglaser** [comment]
Yeah, let's do this.

**Comment by BerryTaylor** [comment]
will this mail be published?test... jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 01/24/2020 23:22, Pierre Glaser wrote: Yeah, let's do this. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pierreglaser** [comment]
you can email me at: pierreglaser@msn.com

**Comment by pierreglaser** [comment]
https://whereby.com/pierreglaser

**Comment by BerryTaylor** [comment]
Sorry , the video may not be convenient to open now, coz I am now in a dark dorm..(with lights off

**Comment by pierreglaser** [comment]
It's fine, turn the video off and simply share your screen.

**Comment by BerryTaylor** [comment]
you know TeamViewer? simply use my Id and password. or in which way will you prefer to be shared the screen with? jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 01/24/2020 23:34, Pierre Glaser wrote: It's fine, simply share your screen. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BerryTaylor** [comment]
at the same time we can use the text editor to communicate jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 01/24/2020 23:37, jnwengang@pku.edu.cn wrote: you know TeamViewer? simply use my Id and password. or in which way will you prefer to be shared the screen with? jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 01/24/2020 23:34, Pierre Glaser wrote: It's fine, simply share your screen. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BerryTaylor** [comment]
do you have accounts of any social network...?I may need to sleep later, it will be far more convenient if we can connect on the social network jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 01/24/2020 23:39, jnwengang@pku.edu.cn wrote: at the same time we can use the text editor to communicate jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 01/24/2020 23:37, jnwengang@pku.edu.cn wrote: you know TeamViewer? simply use my Id and password. or in which way will you prefer to be shared the screen with? jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 01/24/2020 23:34, Pierre Glaser wrote: It's fine, simply share your screen. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by BerryTaylor** [comment]
Yes! It did work!And work quite perfectly!

**Comment by pierreglaser** [comment]
Great! Can you remove your screenshots/comments in https://github.com/gillescastel/inkscape-figures/pull/11? In order to limit the amount of noise in this discussion.

**Comment by pierreglaser** [comment]
Great. closing.

**Comment by BerryTaylor** [comment]
Sure！ sorry for delay, I have just slept for the whole night... jnwengang 邮箱jnwengang@pku.edu.cn 签名由 网易邮箱大师 定制 On 01/25/2020 00:41, Pierre Glaser wrote: Great! Can you remove your screenshots/comments in gillescastel#11? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
